### ISSUE TITLE
InsertIfNotExists / PutIfNotExists / Initialization of buckets

### ISSUE THREAD

**Issue by arvenil** [joyrexus/buckets#2]
`boltdb` suggest that after opening db we should create buckets if they not exists.
I came to the same conclusion but for bucket structure. So, let's say I have a bucket `UserProfile`, when I first open db I would like it to create that bucket with some defaults, but after that, whenever I open db again the data should not be overwritten. So I would like to have something like InsertIfNotExists, which first gets the data and then if keys doesn't exists - inserts defaults.

Does this make sense? :)

**Comment by joyrexus** [comment]
Hmm.  Not sure I follow.  When you say ...

> I would like to have something like InsertIfNotExists, which first gets the data and then if keys doesn't exists - inserts defaults.

... I gather you're talking about bucket gets.  So, is the idea you're proposing that if you're retrieving a key, if the key doesn't exist it's automatically inserted into the bucket with a default value ... or, rather, that the `bucket.Get(key)` just returns a default value for non-existent keys.  I'm not sure I see the value proposition of having something baked in for either case, but let me know if I'm just misunderstanding your suggestion.

**Comment by joyrexus** [comment]
Closing for now.  Will re-open if question is clarified.

**Comment by arvenil** [comment]
Defaults: yes; Get: no

Something like this: http://redis.io/commands/setnx
So let's say you use `PutNX(k, v)` then if key doesn't exist, it creates one, if it exist, nothing happens.
This would be especially powerful as `Insert(items)` (e.g. `InsertNX(items)`) as you could easily initialize whole buckets.

Right now I need to:
1. get key to check if it exist
2. if not create it with given ~~default~~ value
3. repeat as many times as many keys you have

**Comment by joyrexus** [comment]
Ah, I do see the potential value of `PutNX(k, v)` and `InsertNX(items)` where they put/insert when a key doesn't already exist.

The only thing I'm still a little unsure about is your use of the term "default", as in ...

> if not, create it with _default_ value.
> 
> I would like to have something like InsertIfNotExists, which first gets the data and then if keys doesn't exists - inserts _defaults_.

The way I would envision `PutNX(k, v)` working is that it would put the provided value `v` with the associated key `k` if `k` does not exist. `InsertNX(items)` would work along the same lines, on an item by item basis, where an item is a `(k, v)` pair.

In both cases, we put/insert the provided value if the associated key doesn't exist ... not some default value.  Let me know if that's actually what you meant or I'm still misunderstanding something.

**Comment by arvenil** [comment]
ignore term `default` ;) and yes `PutNX(k, v)` and `InsertNX(items)` is what I would like to have

**Comment by joyrexus** [comment]
Sounds good.  I've added `PutNX` and plan to add `InsertNX` too.

**Comment by joyrexus** [comment]
`InsertNX` added.  Let me know how it works out for you.
